### ISSUE TITLE
Support for categorical columns

### ISSUE THREAD

**Issue by saikiran1201** [predict-idlab/powershap#25]
By default CatBoost accepts categorical columns. Can we expect support for powershap as well.

**Comment by JarneVerhaeghe** [comment]
Hi @saikiran1201,

Sorry for the late reply!
Powershap supports this already. However, while using Powershap the code deletes the feature names for compatibility, and therefore it will not work to specify the feature names in the _cat_features_ argument of CatBoost. A workaround is to use the column index of the categorical column. So suppose your categorical features have column index 4 and column index 6 in your pandas columns, then you can just specify it as follows and it will work:

`selector = PowerShap(
    model = CatBoostClassifier(cat_features=[4,6]),
)`

I hope this answers your question.
