### ISSUE TITLE
PyPI brownout for `sklearn` in favor of `scikit-learn`

### ISSUE THREAD

**Issue by deepandas11** [predict-idlab/powershap#26]
Hi!

Appreciate the work on this project. 

`scikit-learn` [announced a gradual brownout](https://github.com/scikit-learn/sklearn-pypi-package) of the `sklearn` dependency from PyPI. Even though the `main` branch on this repository tags `scikit-learn` correctly, the latest release on PyPI(`rc2`), still lists it as `sklearn`. 

We had a [discussion](https://github.com/predict-idlab/powershap/pull/22#discussion_r926394447) about this on this [PR](https://github.com/predict-idlab/powershap/pull/22), but I believe a release was tagged before the `sklearn` -> `scikit-learn` change was made. 

Can we expect a new release being tagged and pushed to PyPI before 12/01? 

Thanks!

**Comment by jvdd** [comment]
Hey @deepandas11,

Thx for letting us know about the brownout :) 

I just released powershap `v0.0.8`. Can you confirm that this version has the correct (`scikit-learn`) tag?

**Comment by deepandas11** [comment]
> I just released powershap `v0.0.8`. Can you confirm that this version has the correct (`scikit-learn`) tag?

Appreciate looking into this quickly. This works now, as expected. 

Will be closing this issue.
