### ISSUE TITLE
Support pandas 2.0

### ISSUE THREAD

**Issue by almostintuitive** [predict-idlab/powershap#39]
Hi! Thank you creating this library, it's super useful!

We're using it with pandas 2.0, without any errors so far. Would it be possible to relax the version constraints, to enable usage with the new major version?

Thank you!

**Comment by almostintuitive** [comment]
created a PR #40

**Comment by jvdd** [comment]
Will close this issue as soon as we publish a new release! :)

**Comment by jonasvdd** [comment]
Fixed with latest release `0.10.0`!
